### ISSUE TITLE
Nodo failed to load when package.json type: module is used

### ISSUE THREAD

**Issue by bogdan** [mtgrosser/nodo#6]
Nodo failed to precompiling assets when `type: "module"` is set in `package.json`:

```
remote:        node:internal/modules/cjs/loader:1544
remote:              throw err;
remote:              ^
remote:
remote:        Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/nodo.js from /tmp/build_1e6ae3ee/[eval] not supported.
remote:        nodo.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
remote:        Instead either rename nodo.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /tmp/build_1e6ae3ee/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
remote:
remote:            at [eval]:1:15
remote:            at [eval]-wrapper:6:24 {
remote:          code: 'ERR_REQUIRE_ESM'
remote:        }
remote:
remote:        Node.js v20.17.0
remote:        rake aborted!
remote:        Nodo::TimeoutError: could not connect to socket /tmp/nodo20240926-1787-2iq44d/nodo.sock (Nodo::TimeoutError)
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/core.rb:230:in `wait_for_socket'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/core.rb:147:in `block in initialize'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/core.rb:145:in `synchronize'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/core.rb:145:in `initialize'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/core.rb:30:in `new'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/nodo-1.6.5/lib/nodo/core.rb:30:in `instance'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:33:in `call'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:184:in `load_from_unloaded'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
remote:        /tmp/build_1e6ae3ee/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
```

I think the easiest way to fix it is to rename `nodo.js` to `nodo.cjs`, but ideally it should be migrated to ESM.

**Comment by mtgrosser** [comment]
Thank you for your PR, released 1.7.0
